spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: auth-flow
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: auth_event
    open-in-view: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/base-event?currentSchema=auth_event
    username: henry
    password: 123456
  messages:
    encoding: UTF-8
    basename: vi
server:
  port: 8002


henry:
  auth-command:
    api: localhost:8001
  auth-query:
    api: localhost:8003
  environment:
    debug: true
  elasticsearch:
    port: 9200
    host: localhost
  connector:
    db-port: 5432
    db-name: base-event
    server-id: 184054
    url: "http://localhost:8083/connectors"