spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: auth-flow
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: auth_event
    open-in-view: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DOCKER_POSTGRES_URL}/henry-event?currentSchema=auth_event
    username: ${DOCKER_POSTGRES_USERNAME}
    password: ${DOCKER_POSTGRES_PASSWORD}
server:
  port: 8002


henry:
  auth-command:
    api: localhost:8001
  auth-query:
    api: localhost:8003
  environment:
    debug: ${DEBUG}