spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: auth-command
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: auth_event
    open-in-view: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/henry-event?currentSchema=auth_event
    username: henry
    password: 123456
  messages:
    encoding: UTF-8
    basename: vi
server:
  port: 8001

henry:
  auth-command:
    api: localhost:8001
  auth-query:
    api: localhost:8003
  prefix:
    api: api
  environment:
    debug: true
  elasticsearch:
    port: 9200
    host: localhost
  jwt:
    secret-key: 60ce8ae1790dfc0fccf946d2c7ba27d4cac35c1b360ae585b7e90dd958f6c859b614fc233290a4d7912bc5deddefc57851f7eaa6c179e1bc23351a7bde7603e2
