spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: auth-command
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: auth_event
    open-in-view: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${dockerPostgresUrl}/${dockerPostgresDatabase}?currentSchema=auth_event
    username: ${dockerPostgresUsername}
    password: ${dockerPostgresPassword}
server:
  port: 8001

henry:
  auth-command:
    api: localhost:8001
  auth-query:
    api: localhost:8003
  prefix:
    api: ${prefixUrl}
  environment:
    debug: ${debug}