spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: auth-command
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: auth_event
    open-in-view: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/base-event?currentSchema=auth_event
    username: base
    password: 123456
  messages:
    encoding: UTF-8
    basename: vi
  elasticsearch:
    uris: http://localhost:9200
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8001
grpc:
  server:
    port: 8011
base:
  environment:
    debug: true
