spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: auth-query
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: auth_event
    open-in-view: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/base-event?currentSchema=auth_event
    username: base
    password: 123456
  elasticsearch:
    uris: http://localhost:9200
  data:
    redis:
      host: localhost
      port: 6379
  messages:
    basename: vi
server:
  port: 8003
grpc:
  client:
    auth-query:
      address: 'static://localhost:9090'
      negotiationType: plaintext
base:
  environment:
    debug: true