spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: auth-query
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: auth_event
    open-in-view: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/henry-event?currentSchema=auth_event
    username: henry
    password: 123456
  elasticsearch:
    uris: localhost:9200
server:
  port: 8003

base:
